apiVersion: v1
kind: Service
metadata:
  name: sidecar-injector-webhook-svc
  labels:
    app: sidecar-injector
spec:
  ports:
  - port: 8443
    targetPort: 8888
  selector:
    app: sidecar-injector
